In [1]:
import torch
import numpy as np

In [2]:
np.set_printoptions(precision = 3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype = np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

t_ones = torch.ones(2, 3)

t_rand = torch.rand(2, 3)

print(t_a)
print(t_b)

print("\nt_ones")
print(t_ones.shape)
print(t_ones)

print("\nt_rand")
print(t_rand)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)

t_ones
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])

t_rand
tensor([[0.6784, 0.5891, 0.5242],
        [0.5914, 0.9370, 0.3852]])
